spring:
  application:
    name: election-api
  main:
    lazy-initialization: true

  data:
    mongodb:
      uri: ${MONGO_URI}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

electoral:
  scoring:
    judicial:
      base-score: 100.0
      penalties:
        - status: SENTENCIA_FIRME_CONDENATORIA
          severity: GRAVE
          value: 50.0
        - status: SENTENCIA_PRIMERA_INSTANCIA
          severity: GRAVE
          value: 35.0
        - status: PROCESO_JUDICIAL_ABIERTO
          severity: GRAVE
          value: 20.0
        - status: INVESTIGACION_PRELIMINAR
          severity: GRAVE
          value: 10.0

        - status: SENTENCIA_FIRME_CONDENATORIA
          severity: MODERADO
          value: 30.0
        - status: SENTENCIA_PRIMERA_INSTANCIA
          severity: MODERADO
          value: 21.0
        - status: PROCESO_JUDICIAL_ABIERTO
          severity: MODERADO
          value: 12.0
        - status: INVESTIGACION_PRELIMINAR
          severity: MODERADO
          value: 6.0

        - status: SENTENCIA_FIRME_CONDENATORIA
          severity: LEVE
          value: 10.0
        - status: SENTENCIA_PRIMERA_INSTANCIA
          severity: LEVE
          value: 7.0
        - status: PROCESO_JUDICIAL_ABIERTO
          severity: LEVE
          value: 4.0
        - status: INVESTIGACION_PRELIMINAR
          severity: LEVE
          value: 2.0
    contribution:
      max-sub-score: 50.0
      max-years-experience: 10
      max-items-allowed: 5
      bonuses:
        academic:
          doctorate: 25.0
          mastery: 15.0
          bachelor: 8.0
        social-leadership: 15.0
        relevance:
          high: 15.0
          medium: 7.0
          low: 2.0
      penalties:
        promise-broken: 20.0

    transparency:
      declaration-base: 15.0
      inconsistency-bonuses:
        0: 10.0
        1: 5.0
        2: 0.0
      economic-info-item: 5.0
      attendance-weight: 0.1
      default-attendance-point: 8.0

    trust:
      initial-score: 100.0
      penalties:
        major-scandal: 30.0
        minor-controversy: 10.0
        fact-check-max: 25.0
        fact-check-unit: 5.0
        ethics-sanction: 25.0
        party-switches:
          0: 0.0
          1: 5.0
          2: 15.0
          3: 30

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.mongodb.driver: WARN


