server:
  port: 8080

spring:
  application:
    name: election-api

  data:
    mongodb:
      uri: ${MONGO_URI}
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: INFO

